name: lottus
description: >-
  An opinionated backend framework for Dart inspired by NestJS and other popular projects around
  focusing on building scalable, modular and maintainable applications with the best developer experience possible.
version: 1.0.0

environment:
  sdk: ^3.2.3

dev_dependencies:
  lints: ^2.1.0
  melos: ^3.4.0
  test: ^1.24.0
